<?php
declare(strict_types=1); require_once __DIR__.'/config.php';
if(session_status()!==PHP_SESSION_ACTIVE){session_name(ADMIN_SESSION_NAME);session_start(['cookie_httponly'=>true,'cookie_samesite'=>'Strict']);}
function h($v){return htmlspecialchars((string)$v,ENT_QUOTES|ENT_SUBSTITUTE,'UTF-8');}
function is_logged_in():bool{return !empty($_SESSION['admin_logged_in']);}
function require_login():void{if(!is_logged_in()){header('Location: login.php');exit;}}
function csrf_token():string{if(empty($_SESSION['csrf']))$_SESSION['csrf']=bin2hex(random_bytes(32));return $_SESSION['csrf'];}
function verify_csrf():void{$t=$_POST['csrf']??$_SERVER['HTTP_X_CSRF_TOKEN']??'';if(!hash_equals($_SESSION['csrf']??'',$t)){http_response_code(403);exit('Invalid CSRF token');}}
function load_db():array{$raw=file_get_contents(DATABASE_PATH);$d=json_decode($raw,true);if(!is_array($d))throw new RuntimeException('Invalid JSON');if(!isset($d['words']))$d=['version'=>'imported','total_unique'=>count($d),'levels'=>[],'words'=>$d];return $d;}
function backup_db():?string{if(!file_exists(DATABASE_PATH))return null;if(!is_dir(BACKUP_DIR))mkdir(BACKUP_DIR,0755,true);$f=BACKUP_DIR.'/database-'.date('Y-m-d-H-i-s').'.json';copy(DATABASE_PATH,$f);return $f;}
function list_backups():array{$b=glob(BACKUP_DIR.'/database-*.json')?:[];rsort($b);return $b;}
function prune_backups():void{global $SETTINGS;foreach(array_slice(list_backups(),(int)($SETTINGS['backup_count']??30)) as $f)@unlink($f);}
function save_db(array $db):void{backup_db();$db['total_unique']=count($db['words']??[]);$json=json_encode($db,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_PRETTY_PRINT);$tmp=DATABASE_PATH.'.tmp';file_put_contents($tmp,$json,LOCK_EX);rename($tmp,DATABASE_PATH);prune_backups();}
function stats(array $db):array{$s=['total'=>0,'levels'=>[1=>0,2=>0,3=>0,4=>0,5=>0],'Extra'=>0,'missing_bangla'=>0,'missing_bp'=>0,'missing_audio'=>0,'missing_examples'=>0,'categories'=>[],'pos'=>[],'recent'=>[]];$w=$db['words']??[];$s['total']=count($w);$s['recent']=array_slice(array_reverse($w),0,8);foreach($w as $x){$l=(int)($x['level']??0);isset($s['levels'][$l])?$s['levels'][$l]++:$s['Extra']++;if(trim((string)($x['bangla']??''))==='')$s['missing_bangla']++;if(trim((string)($x['bangla_pronunciation']??''))==='')$s['missing_bp']++;if(trim((string)($x['audio']??''))===''||!file_exists(__DIR__.'/../'.ltrim((string)$x['audio'],'/')))$s['missing_audio']++;if(empty($x['examples']))$s['missing_examples']++;$c=$x['category']??'Uncategorized';$p=$x['part_of_speech']??'';$s['categories'][$c]=($s['categories'][$c]??0)+1;$s['pos'][$p]=($s['pos'][$p]??0)+1;}ksort($s['categories']);ksort($s['pos']);return $s;}
function find_word_index(array $words,$id):int{foreach($words as $i=>$w)if((string)($w['id']??'')===(string)$id)return $i;return -1;}
function sanitize_word(array $in):array{$ex=[];foreach(($in['examples']??[]) as $e)$ex[]=['hanzi'=>trim((string)($e['hanzi']??'')),'pinyin'=>trim((string)($e['pinyin']??'')),'bangla_pronunciation'=>trim((string)($e['bangla_pronunciation']??'')),'english'=>trim((string)($e['english']??'')),'bangla'=>trim((string)($e['bangla']??''))];return ['id'=>(int)($in['id']??0),'level'=>is_numeric($in['level']??null)?(int)$in['level']:$in['level'],'hanzi'=>trim((string)($in['hanzi']??'')),'traditional'=>trim((string)($in['traditional']??'')),'pinyin'=>trim((string)($in['pinyin']??'')),'bangla_pronunciation'=>trim((string)($in['bangla_pronunciation']??'')),'english'=>trim((string)($in['english']??'')),'bangla'=>trim((string)($in['bangla']??'')),'category'=>trim((string)($in['category']??'')),'part_of_speech'=>trim((string)($in['part_of_speech']??'')),'audio'=>trim((string)($in['audio']??'')),'stroke_count'=>is_numeric($in['stroke_count']??null)?(int)$in['stroke_count']:0,'radical'=>trim((string)($in['radical']??'')),'examples'=>$ex];}
function layout_header($title){global $SETTINGS;require __DIR__.'/partials_header.php';} function layout_footer(){require __DIR__.'/partials_footer.php';}
?>